load_mets_map() = load_data(METS_MAP_FILE; verbose = false)
load_exch_met_map() = load_data(EXCH_MET_MAP_FILE; verbose = false)
load_niklas_biomass() = load_data(NIKLAS_BIOMASS_FILE; verbose = false)
load_base_intake_info() = load_data(BASE_INTAKE_INFO_FILE; verbose = false)
load_base_model() = load_data(MODEL_PROCESSED_DATA_DIR; verbose = false)
load_fva_pp_base_model() = load_data(FVA_PP_BASE_MODEL_FILE; verbose = false)